import type { Language } from "./language";

export const APP_COPY = {
  it: {
    common: {
      skip: "Vai al contenuto",
      preciseValue: "Valore preciso",
      numericEntry: "inserimento numerico",
      openMethod: "Apri il metodo",
      reset: "reset",
      notAvailable: "n.d.",
      years: "anni",
      million: "milioni",
    },
    truth: {
      FATTO: "FATTO",
      "PROIEZIONE UFFICIALE": "PROIEZIONE UFFICIALE",
      "STIMA DEL MODELLO": "STIMA DEL MODELLO",
      SCENARIO: "SCENARIO",
      "ANALOGIA RETORICA": "ANALOGIA RETORICA",
    },
    nav: [
      { id: "alert", label: "L'allarme", mobileLabel: "Allarme", number: "1" },
      { id: "anni", label: "I tuoi anni", mobileLabel: "I tuoi anni", number: "2" },
      { id: "patto", label: "Il patto", mobileLabel: "Patto", number: "3" },
      { id: "pressione", label: "La pressione", mobileLabel: "Pressione", number: "4" },
      { id: "risultato", label: "Il risultato", mobileLabel: "Risultato", number: "5" },
      { id: "leve", label: "Le leve", mobileLabel: "Leve", number: "6" },
      { id: "confronto", label: "Il confronto", mobileLabel: "Confronto", number: "7" },
      { id: "fonti", label: "Fonti", mobileLabel: "Fonti", number: "∞" },
    ],
    header: {
      brandTop: "IL CONTO",
      brandBottom: "DELLA PENSIONE",
      home: "Torna all'inizio",
      navigation: "Navigazione narrativa",
      mobileLabel: "Vai a una sezione",
      language: "Lingua del sito",
      italian: "Italiano",
      english: "Inglese",
    },
    loading: {
      brand: "IL CONTO DELLA PENSIONE",
      errorTitle: "Il dato non arriva. Il conto resta leggibile.",
      title: "Stiamo aprendo i registri.",
      body: "Carichiamo i pack pubblici, poi puoi cambiare le leve. Nessun dato personale esce dal tuo browser.",
      unavailable: "I pack dati non sono disponibili.",
      failed: "I pack pubblici non si sono caricati. Controlla che il server locale stia servendo /data e riprova.",
      retry: "Riprova",
      progress: "Caricamento dati",
    },
    hero: {
      alert: "Nessun conto alla rovescia. Il problema è già nel flusso.",
      eyebrow: "DATI, SCENARI, COMPROMESSI",
      updated: "aggiornato al 23 agosto 2026",
      titleStart: "La pensione non esplode.",
      titleEmphasis: "Si restringe,",
      titleEnd: "busta paga dopo busta paga.",
      lead: "Non serve indovinare il giorno del disastro. Serve capire chi versa, chi riceve e quali regole spostano il conto.",
      rhetorical: "La frase è una provocazione editoriale, non una previsione.",
      cta: "Scorri il conto",
      factsAria: "Tre fatti di contesto",
      benefitsLabel: "prestazioni INPS in vigore",
      benefitsNote: "Contate come prestazioni, non come persone.",
      peakLabel: "picco spesa pubblica sul PIL",
      peakNote: "Baseline Ageing Report, anno 2036.",
      populationLabel: "residenti nello scenario Istat 2050",
      populationNote: "Scenario mediano, milioni di persone.",
    },
    personal: {
      kicker: "I tuoi anni",
      titleStart: "Il tuo futuro non arriva a 67 anni.",
      titleEmphasis: "Comincia dal primo versamento.",
      intro: "Metti cinque numeri nel conto. Il risultato è un assegno simulato in euro costanti 2026, non il tuo estratto conto INPS.",
      inputs: "Input personali",
      local: "calcolo locale",
      age: "Quanti anni hai?",
      salary: "Quanto guadagni lordi?",
      salaryHelp: "Euro costanti 2026, prima di imposte e contributi.",
      career: "A che età hai iniziato a versare?",
      contributed: "Anni di contributi già indicati",
      growth: "Crescita reale annua dello stipendio",
      growthHelp: "È una scelta di scenario, non una promessa di carriera.",
      advanced: "Ipotesi avanzate",
      retirement: "Età di pensionamento simulata",
      retirementHelp: "La regola ordinaria INPS è 67 anni nel 2026. Il futuro può cambiare.",
      rate: "Aliquota contributiva",
      benefit: "Fattore della prestazione pubblica",
      funded: "Quota di contribuzione finanziata",
      output: "Output locale, aggiornato ora",
      outputLead: "Con queste ipotesi, l'assegno simulato sarebbe",
      perMonth: "al mese",
      grossAnnual: "lordi all'anno, in euro costanti 2026",
      liveStart: "Output aggiornato: assegno simulato di",
      liveMiddle: "al mese",
      liveEnd: "lordi all'anno.",
      methodTitle: "Le ipotesi del calcolo personale",
      methodOne: "Il modello somma i versamenti pubblici e una quota finanziata separata. Trasforma il saldo in una rendita reale su 22 anni. Il rendimento finanziato ipotizzato è del 3% reale annuo.",
      methodTwo: "Non calcola tasse, commissioni, reversibilità, invalidità, minimi, carriere discontinue o coefficienti INPS. La crescita prima dell'anno corrente è ricostruita a ritroso dal tuo stipendio dichiarato. È un dispositivo didattico.",
      formula: "pensione = fattore pubblico × saldo pubblico / 22 + saldo finanziato × rendita al 3%",
    },
    pact: {
      kicker: "Il patto",
      titleStart: "Ogni pensione futura dipende da redditi, lavoro e regole che ancora",
      titleEmphasis: "non conosciamo.",
      intro: "Il PAYG non è un salvadanaio personale. I contributi di oggi finanziano le prestazioni di oggi, dentro conti pubblici più ampi.",
      workers: "milioni di occupati",
      baseline: "baseline Ageing Report",
      noData: "dato non disponibile nel pack",
      sourceId: "sourceId",
      unit: "unità",
      scope: "perimetro",
      pensioners: "milioni di pensionati",
      unique: "beneficiari unici, 2024",
      ratioNote: "È un rapporto orientativo. Le due serie non hanno la stessa definizione statistica.",
      contributions: "di contributi nel 2025",
      outlaysStart: "Le prestazioni pensionistiche INPS registrate nel bilancio sono",
      outlaysEnd: "Confrontare due righe non equivale a calcolare un disavanzo.",
      observedRule: "Regola osservata",
      observedRuleText: "Vecchiaia ordinaria: 67 anni e 20 di contributi nel 2026",
      nextSteps: "Prossimi scatti",
      nextStepsText: "67 anni e 1 mese nel 2027, 67 anni e 3 mesi nel 2028",
      methodTitle: "Perché il patto è più grande del grafico",
      methodOne: "Il bilancio INPS usa conti di competenza. Dentro ci sono trasferimenti statali, assistenza e più gestioni. La storia sopra serve a leggere il flusso, non a sostituire i conti nazionali.",
      methodTwo: "La formula contributiva italiana capitalizza i contributi a un tasso legato alla crescita nominale del PIL e applica coefficienti legati a mortalità e speranza di vita. Le regole miste dipendono dalla storia contributiva.",
      footnote: "Nel grafico: entrate correnti totali, contributi e trasferimenti. Anni e unità restano visibili nelle etichette della fonte.",
    },
    pressure: {
      kicker: "La pressione",
      titleStart: "Meno persone in età lavorativa.",
      titleEmphasis: "Più persone fuori dal lavoro.",
      intro: "È una traiettoria pubblicata, non una profezia. Cambia se cambiano nascite, migrazioni, occupazione, produttività e regole.",
      peak: "Il punto più alto nel baseline",
      gdp: "del PIL",
      peakNote: "spesa pubblica lorda",
      omission: "Quello che il grafico non dice",
      noDate: "non c'è una data magica",
      noCountdown: "un modello condizionale non è un conto alla rovescia",
      methodTitle: "Leggere una proiezione senza trasformarla in profezia",
      methodOne: "Il baseline Ageing Report raggiunge il picco di spesa lorda nel 2036 e poi scende nel suo percorso di policy. Istat, con un'altra popolazione di base e un altro modello, porta i residenti a 54,7 milioni nel 2050 nello scenario mediano.",
      methodTwo: "Le bande di incertezza Istat per il 2050 vanno da 52,5 a 56,8 milioni. Sono scenari ufficiali, non probabilità su cui puntare una data.",
    },
    result: {
      kicker: "Il risultato",
      titleStart: "Adesso metti il tuo numero",
      titleEmphasis: "nel conto.",
      intro: "Un output leggibile vale più di un numero urlato. Qui vedi anche cosa resta fuori.",
      annualPension: "Pensione annua simulata",
      monthConversion: "al mese, conversione su 12 mesi",
      replacement: "Tasso di sostituzione lordo",
      finalSalary: "su uno stipendio finale di",
      annualContribution: "Contributo annuo oggi",
      grossSalary: "dello stipendio lordo",
      simulatedPayments: "Versamenti simulati",
      public: "pubblici",
      funded: "finanziati",
      pressureAtYear: "Pressione al tuo anno",
      pressureNote: "Indice del modello macro, base 2025 = 1,00",
      controlled: "Confronto controllato",
      sameInputs: "Stesse ipotesi, età diverse",
      comparisonNote: "Non sono tre persone reali. Cambia solo l'età e il tempo residuo, mentre stipendio, carriera e leve restano leggibili.",
      simulatedMonthly: "al mese simulati",
      retirement: "ritiro a",
      calloutTitle: "Un importo alto è una distribuzione, non una sentenza.",
      calloutBody: "Le combinazioni tra vecchiaia, reversibilità, invalidità e assistenza possono essere previste dalle regole. I dati non dimostrano da soli un abuso.",
      methodTitle: "I limiti da tenere accanto al risultato",
      methodOne: "Il risultato non si chiama pensione INPS perché non ricostruisce la tua posizione, la tua gestione, la fiscalità o la storia dei contributi. È uno scenario didattico in euro costanti 2026.",
      methodTwo: "Il dato INPS 2024 distingue 16,306 milioni di beneficiari unici da 23,015 milioni di prestazioni. Le bande di importo descrivono unità diverse e non si possono sommare senza controllare le sovrapposizioni.",
    },
    macro: {
      kicker: "Le leve",
      titleStart: "Sposta una leva.",
      titleEmphasis: "Guarda quale prezzo compare.",
      intro: "Questo simulatore non predice. Tiene ferme le altre variabili e mostra la direzione di un compromesso.",
      presetsAria: "Scenari preimpostati",
      shortcuts: "Scorciatoie:",
      start: "Scenario di partenza",
      workers: "Più persone al lavoro",
      output: "Più valore per ora",
      later: "Tre anni in più",
      funded: "Più capitale, più transizione",
      visible: "Leve visibili",
      employment: "Crescita annua dell'occupazione",
      migration: "Migrazione netta nel bacino di lavoro",
      thousandYear: "mila/anno",
      productivity: "Crescita reale della produttività",
      retirement: "Età media di pensionamento simulata",
      retirementHelp: "La sensibilità dell'occupazione è una scelta del modello.",
      rate: "Aliquota contributiva",
      benefit: "Fattore della prestazione",
      indexation: "Quota crescita trasferita alle prestazioni",
      fundedShare: "Quota finanziata",
      fundedHelp: "Devia il flusso corrente nel modello. Non sostituisce subito le prestazioni PAYG.",
      pressure: "pressione",
      base: "base = 1,00",
      requiredRate: "aliquota necessaria",
      systemPressure: "Pressione del sistema",
      systemPressureNote: "2050, indice base 2025 = 1,00",
      workersPerBeneficiary: "Occupati per beneficiario",
      proxy2050: "proxy nel 2050",
      paygRate: "Aliquota PAYG necessaria",
      wageBill: "monte salari modellato",
      flowBalance: "Bilancio di flusso proxy",
      equalFlows: "1,00 significa flussi uguali",
      averageReplacement: "Sostituzione media proxy",
      benefitWage: "prestazione / salario",
      fundedFlow: "Flusso finanziato",
      ofContributions: "dei contributi",
      band: "Banda di scenario al 2050",
      low: "Basso",
      central: "Centrale",
      high: "Alto",
      bandNote: "La banda varia occupazione di ±0,5 punti, migrazione di ±50 mila persone, crescita dei beneficiari di ±0,2 punti e produttività di ±0,5 punti. Non è una distribuzione di probabilità.",
      generational: "Confronto generazionale",
      samePolicy: "stessa politica, anni di ritiro diversi",
      retirementShort: "ritiro",
      workerShort: "occupati / beneficiario",
      replacementShort: "sostituzione",
      readoutStart: "Nel 2050, con queste leve, il flusso copre",
      readoutEnd: "della spesa modellata.",
      readoutNote: "Pressione, aliquota, sostituzione e bilancio sono proxy. Non sono la contabilità dello Stato.",
      liveStart: "Simulatore macro aggiornato: pressione",
      liveRate: "aliquota PAYG necessaria",
      liveReplacement: "sostituzione media",
      transitionTitle: "La quota finanziata non cancella il PAYG domani mattina.",
      transitionBody: "Se una parte dei contributi correnti va in un conto finanziato, le promesse PAYG già maturate restano da pagare. Per la transizione serve un'altra fonte di finanziamento: più imposte, più debito, più spesa pubblica o un passaggio graduale.",
      methodTitle: "Formula e limiti del modello macro",
      methodStart: "La calibrazione usa una base occupazionale come proxy. Il riferimento ufficiale disponibile nel pack è",
      unavailable: "non disponibile",
      inUnit: "in",
      forScope: "per il perimetro",
      unitMissing: "unità non indicata",
      scopeMissing: "non indicato",
      methodEnd: "Beneficiari e reddito pensionistico annualizzato hanno serie e definizioni diverse.",
      formula: "E(t+1) = E(t) × (1 + crescita occupazione) + migrazione\npressione = (beneficiari / occupati) / rapporto di base\naliquota PAYG necessaria = uscite modellate / monte salari",
      elasticity: "L'età di pensionamento modifica occupati e beneficiari con elasticità didattiche fissate dal modello. Non sono elasticità ufficiali. Gli scenari non hanno probabilità.",
    },
    comparison: {
      kicker: "Il confronto",
      titleStart: "Tre paesi.",
      titleEmphasis: "Tre modi di distribuire il rischio.",
      intro: "Non c'è un paese con il pulsante \"risolto\". Ci sono pilastri diversi, regole diverse e rischi spostati in posti diversi.",
      architectures: "Architetture, non classifiche",
      whoPays: "Chi paga cosa",
      matrixIntro: "Il primo pilastro svizzero è PAYG. Gli asset enormi appartengono soprattutto al secondo pilastro finanziato.",
      scroll: "Su schermi stretti, scorri orizzontalmente per confrontare tutti i paesi.",
      tableAria: "Confronto dei pilastri pensionistici",
      pillar: "Pilastro",
      swissTitle: "Il caso svizzero corregge un equivoco comune.",
      swissBody: "Un sistema può avere grandi asset finanziati e mantenere un primo pilastro pubblico a ripartizione. Passare da PAYG a finanziato può aumentare il capitale nel tempo, ma nel passaggio crea un buco da finanziare. Non è magia contabile.",
      closing: "La chiusura",
      closingTitle: "Nessuna data magica.",
      closingEmphasis: "Solo pressione misurabile.",
      closingBody: "Puoi cambiare il modello. Non puoi farlo diventare una profezia. Il punto della pensione è distribuire un rischio lungo decenni, non indovinare un giorno sul calendario.",
      sourcesCta: "Vedi fonti e metodo",
      countryNames: { IT: "Italia", CH: "Svizzera", SE: "Svezia", NL: "Paesi Bassi" },
      countryDescriptions: {
        CH: "Tre pilastri: AVS/OASI pubblico a ripartizione, previdenza professionale finanziata sopra la soglia prevista e risparmio individuale volontario.",
        SE: "Pensione pubblica NDC a ripartizione, premio finanziato, garanzia pubblica e una previdenza occupazionale molto diffusa.",
        NL: "AOW pubblico a ripartizione, previdenza occupazionale finanziata e prodotti individuali. Il pilastro occupazionale passa verso contributi definiti.",
      },
      countryLines: {
        CH: { title: "Primo pilastro a ripartizione", body: "Le contribuzioni correnti vanno ai pensionati correnti." },
        SE: { title: "Bilanciamento automatico", body: "L'indice di equilibrio riduce l'indicizzazione se passività e attività divergono." },
        NL: { title: "AOW separata dal pilastro finanziato", body: "La legge del 2023 porta i fondi verso contributi definiti entro il 2028." },
      },
      pillarLabels: {
        first_pillar: "Primo pilastro pubblico",
        second_pillar: "Pilastro occupazionale",
        third_pillar: "Pilastro personale volontario",
      },
    },
    sources: {
      kicker: "Fonti e metodo",
      title: "Il conto è aperto.",
      intro: "Ogni numero qui sopra rimanda a una fonte. Gli anni e i perimetri restano visibili perché il contesto fa parte del dato.",
      vocabulary: "Vocabolario",
      labelsTitle: "Come leggere le etichette",
      labelsBody: "FATTO è osservato. PROIEZIONE UFFICIALE viene da un modello istituzionale. STIMA DEL MODELLO è calcolata qui. SCENARIO è una scelta controllabile. ANALOGIA RETORICA è linguaggio, non statistica.",
      scopes: "Perimetri",
      scopesTitle: "Non sommare mele e persone",
      scopesBody: "Prestazioni, pensionati unici, beneficiari di categoria, conti INPS, ESSPROS e Ageing Report hanno definizioni diverse. Un valore non diventa falso perché un'altra fonte misura un perimetro diverso.",
      privacy: "Privacy",
      privacyTitle: "Nessun dato esce dal browser",
      privacyBody: "Età, stipendio e leve restano nella sessione locale. Il progetto non raccoglie nomi, email, codici fiscali o eventi analitici.",
      footerStart: "Progetto editoriale locale, versione 0.1. Dati caricati da",
      footerMiddle: "e",
      footerEnd: "Il modello non calcola una data di collasso.",
    },
  },
  en: {
    common: {
      skip: "Skip to content",
      preciseValue: "Exact value",
      numericEntry: "numeric entry",
      openMethod: "Open methodology",
      reset: "reset",
      notAvailable: "n/a",
      years: "years",
      million: "million",
    },
    truth: {
      FATTO: "OBSERVED",
      "PROIEZIONE UFFICIALE": "OFFICIAL PROJECTION",
      "STIMA DEL MODELLO": "MODEL ESTIMATE",
      SCENARIO: "SCENARIO",
      "ANALOGIA RETORICA": "EDITORIAL ANALOGY",
    },
    nav: [
      { id: "alert", label: "The warning", mobileLabel: "Warning", number: "1" },
      { id: "anni", label: "Your timeline", mobileLabel: "Timeline", number: "2" },
      { id: "patto", label: "The pact", mobileLabel: "Pact", number: "3" },
      { id: "pressione", label: "The pressure", mobileLabel: "Pressure", number: "4" },
      { id: "risultato", label: "The result", mobileLabel: "Result", number: "5" },
      { id: "leve", label: "The levers", mobileLabel: "Levers", number: "6" },
      { id: "confronto", label: "The comparison", mobileLabel: "Compare", number: "7" },
      { id: "fonti", label: "Sources", mobileLabel: "Sources", number: "∞" },
    ],
    header: {
      brandTop: "THE PENSION",
      brandBottom: "BILL",
      home: "Back to the start",
      navigation: "Story navigation",
      mobileLabel: "Go to a section",
      language: "Site language",
      italian: "Italian",
      english: "English",
    },
    loading: {
      brand: "THE PENSION BILL",
      errorTitle: "The data did not arrive. The account still stays readable.",
      title: "Opening the records.",
      body: "We are loading the public data packs. You can then change the levers. No personal data leaves your browser.",
      unavailable: "The data packs are unavailable.",
      failed: "The public data packs did not load. Check that the local server is serving /data, then try again.",
      retry: "Try again",
      progress: "Loading data",
    },
    hero: {
      alert: "There is no countdown. The problem is already in the flow.",
      eyebrow: "DATA, SCENARIOS, TRADE-OFFS",
      updated: "updated 23 August 2026",
      titleStart: "The pension system does not explode.",
      titleEmphasis: "It narrows,",
      titleEnd: "pay cheque after pay cheque.",
      lead: "There is no need to guess the day of disaster. The useful questions are who pays, who receives and which rules move the bill.",
      rhetorical: "This line is an editorial provocation, not a forecast.",
      cta: "Follow the money",
      factsAria: "Three facts for context",
      benefitsLabel: "INPS benefits currently in force",
      benefitsNote: "Counted as benefits, not people.",
      peakLabel: "peak public pension spending as a share of GDP",
      peakNote: "Ageing Report baseline, 2036.",
      populationLabel: "residents in the 2050 Istat scenario",
      populationNote: "Median scenario, millions of people.",
    },
    personal: {
      kicker: "Your timeline",
      titleStart: "Your future does not begin at 67.",
      titleEmphasis: "It begins with the first contribution.",
      intro: "Enter five numbers. The result is a simulated benefit in constant 2026 euros, not your INPS statement.",
      inputs: "Personal inputs",
      local: "local calculation",
      age: "How old are you?",
      salary: "What is your gross annual salary?",
      salaryHelp: "Constant 2026 euros, before tax and contributions.",
      career: "How old were you when you started contributing?",
      contributed: "Contribution years entered so far",
      growth: "Annual real salary growth",
      growthHelp: "This is a scenario choice, not a career promise.",
      advanced: "Advanced assumptions",
      retirement: "Simulated retirement age",
      retirementHelp: "The standard INPS rule is age 67 in 2026. Future rules can change.",
      rate: "Contribution rate",
      benefit: "Public benefit factor",
      funded: "Funded contribution share",
      output: "Local output, updated now",
      outputLead: "Under these assumptions, the simulated benefit would be",
      perMonth: "per month",
      grossAnnual: "gross per year, in constant 2026 euros",
      liveStart: "Updated output: simulated benefit of",
      liveMiddle: "per month",
      liveEnd: "gross per year.",
      methodTitle: "Assumptions behind the personal calculation",
      methodOne: "The model adds public contributions and a separate funded share. It converts the balance into a real annuity over 22 years. The assumed funded return is 3% a year after inflation.",
      methodTwo: "It does not calculate tax, fees, survivor benefits, disability, minimum benefits, interrupted careers or INPS coefficients. Growth before the current year is reconstructed backwards from the salary you enter. This is a teaching model.",
      formula: "pension = public factor × public balance / 22 + funded balance × annuity at 3%",
    },
    pact: {
      kicker: "The pact",
      titleStart: "Every future pension depends on income, work and rules that we",
      titleEmphasis: "do not know yet.",
      intro: "PAYG is not a personal savings account. Today's contributions finance today's benefits within a wider set of public accounts.",
      workers: "million people in work",
      baseline: "Ageing Report baseline",
      noData: "data unavailable in the pack",
      sourceId: "sourceId",
      unit: "unit",
      scope: "scope",
      pensioners: "million pensioners",
      unique: "unique beneficiaries, 2024",
      ratioNote: "This ratio is only a guide. The two series use different statistical definitions.",
      contributions: "in contributions in 2025",
      outlaysStart: "INPS pension outlays recorded in the accounts are",
      outlaysEnd: "Comparing two lines does not calculate a deficit.",
      observedRule: "Observed rule",
      observedRuleText: "Standard old-age pension: age 67 and 20 contribution years in 2026",
      nextSteps: "Next changes",
      nextStepsText: "67 years and 1 month in 2027, 67 years and 3 months in 2028",
      methodTitle: "Why the pact is larger than this chart",
      methodOne: "INPS accounts use accrual accounting. They include state transfers, assistance and several schemes. The story above explains the flow. It does not replace the national accounts.",
      methodTwo: "Italy's contribution-based formula capitalises contributions at a rate linked to nominal GDP growth and applies coefficients linked to mortality and life expectancy. Mixed rules depend on each contribution history.",
      footnote: "The chart shows total current revenue, contributions and transfers. Source labels keep years and units visible.",
    },
    pressure: {
      kicker: "The pressure",
      titleStart: "Fewer people of working age.",
      titleEmphasis: "More people outside work.",
      intro: "This is a published path, not a prophecy. It changes when births, migration, employment, productivity or policy change.",
      peak: "Highest point in the baseline",
      gdp: "of GDP",
      peakNote: "gross public pension spending",
      omission: "What the chart does not say",
      noDate: "there is no magic date",
      noCountdown: "a conditional model is not a countdown",
      methodTitle: "Reading a projection without turning it into a prophecy",
      methodOne: "The Ageing Report baseline reaches its gross spending peak in 2036, then falls along its policy path. Istat uses a different base population and model. Its median scenario puts the resident population at 54.7 million in 2050.",
      methodTwo: "Istat's 2050 uncertainty range runs from 52.5 to 56.8 million. These are official scenarios, not probabilities for choosing a date.",
    },
    result: {
      kicker: "The result",
      titleStart: "Now place your number",
      titleEmphasis: "inside the bill.",
      intro: "A readable output is worth more than a shouted number. This section also shows what the model leaves out.",
      annualPension: "Simulated annual pension",
      monthConversion: "per month, converted over 12 months",
      replacement: "Gross replacement rate",
      finalSalary: "on a final salary of",
      annualContribution: "Annual contribution today",
      grossSalary: "of gross salary",
      simulatedPayments: "Simulated contributions",
      public: "public",
      funded: "funded",
      pressureAtYear: "Pressure in your retirement year",
      pressureNote: "Macro model index, 2025 base = 1.00",
      controlled: "Controlled comparison",
      sameInputs: "Same assumptions, different ages",
      comparisonNote: "These are not three real people. Only age and remaining time change. Salary, career and policy levers stay visible.",
      simulatedMonthly: "simulated per month",
      retirement: "retirement in",
      calloutTitle: "A high amount is a distribution result, not a verdict.",
      calloutBody: "Old-age, survivor, disability and assistance benefits can overlap under the rules. The data alone do not prove abuse.",
      methodTitle: "Limits to keep beside the result",
      methodOne: "The result is not called your INPS pension because it does not reconstruct your account, scheme, tax position or contribution history. It is a teaching scenario in constant 2026 euros.",
      methodTwo: "The 2024 INPS data distinguish 16.306 million unique beneficiaries from 23.015 million benefits. Amount bands describe different units and cannot be added without checking overlaps.",
    },
    macro: {
      kicker: "The levers",
      titleStart: "Move one lever.",
      titleEmphasis: "See what it costs.",
      intro: "This simulator does not predict. It holds other variables constant and shows the direction of a trade-off.",
      presetsAria: "Preset scenarios",
      shortcuts: "Shortcuts:",
      start: "Starting scenario",
      workers: "More people in work",
      output: "More output per hour",
      later: "Three more years",
      funded: "More funding, more transition",
      visible: "Visible levers",
      employment: "Annual employment growth",
      migration: "Net migration into the labour pool",
      thousandYear: "thousand/year",
      productivity: "Real productivity growth",
      retirement: "Simulated average retirement age",
      retirementHelp: "The employment response is a model choice.",
      rate: "Contribution rate",
      benefit: "Benefit factor",
      indexation: "Share of growth passed to benefits",
      fundedShare: "Funded share",
      fundedHelp: "This diverts current flows inside the model. It does not immediately replace PAYG benefits.",
      pressure: "pressure",
      base: "base = 1.00",
      requiredRate: "required rate",
      systemPressure: "System pressure",
      systemPressureNote: "2050, 2025 base index = 1.00",
      workersPerBeneficiary: "Workers per beneficiary",
      proxy2050: "2050 proxy",
      paygRate: "Required PAYG rate",
      wageBill: "modelled wage bill",
      flowBalance: "Flow balance proxy",
      equalFlows: "1.00 means equal flows",
      averageReplacement: "Average replacement proxy",
      benefitWage: "benefit / wage",
      fundedFlow: "Funded flow",
      ofContributions: "of contributions",
      band: "2050 scenario range",
      low: "Low",
      central: "Central",
      high: "High",
      bandNote: "The range changes employment by ±0.5 points, migration by ±50 thousand people, beneficiary growth by ±0.2 points and productivity by ±0.5 points. It is not a probability distribution.",
      generational: "Generational comparison",
      samePolicy: "same policy, different retirement years",
      retirementShort: "retirement",
      workerShort: "workers / beneficiary",
      replacementShort: "replacement",
      readoutStart: "In 2050, with these levers, the flow covers",
      readoutEnd: "of modelled spending.",
      readoutNote: "Pressure, rates, replacement and balance are proxies. They are not public accounts.",
      liveStart: "Updated macro simulator: pressure",
      liveRate: "required PAYG rate",
      liveReplacement: "average replacement",
      transitionTitle: "A funded share does not erase PAYG tomorrow morning.",
      transitionBody: "If some current contributions go into a funded account, accrued PAYG promises still have to be paid. The transition needs another source of finance: higher taxes, more debt, other public spending or a gradual change.",
      methodTitle: "Macro model formula and limits",
      methodStart: "The calibration uses an employment base as a proxy. The official reference available in the pack is",
      unavailable: "unavailable",
      inUnit: "in",
      forScope: "for the scope",
      unitMissing: "unit not stated",
      scopeMissing: "not stated",
      methodEnd: "Beneficiaries and annualised pension income come from series with different definitions.",
      formula: "E(t+1) = E(t) × (1 + employment growth) + migration\npressure = (beneficiaries / workers) / base ratio\nrequired PAYG rate = modelled outlays / wage bill",
      elasticity: "Retirement age changes workers and beneficiaries through teaching elasticities set by the model. They are not official elasticities. The scenarios have no probabilities.",
    },
    comparison: {
      kicker: "The comparison",
      titleStart: "Three countries.",
      titleEmphasis: "Three ways to distribute risk.",
      intro: "No country has a \"solved\" button. Different pillars and rules move risk to different places.",
      architectures: "Architectures, not rankings",
      whoPays: "Who pays for what",
      matrixIntro: "Switzerland's first pillar is PAYG. Its large assets belong mainly to the funded second pillar.",
      scroll: "On narrow screens, scroll horizontally to compare every country.",
      tableAria: "Comparison of pension pillars",
      pillar: "Pillar",
      swissTitle: "The Swiss case corrects a common misconception.",
      swissBody: "A system can hold large funded assets and keep a public PAYG first pillar. Moving from PAYG to funding can build capital over time, but the transition creates a gap that still needs finance. It is not accounting magic.",
      closing: "Closing note",
      closingTitle: "No magic date.",
      closingEmphasis: "Only measurable pressure.",
      closingBody: "You can change the model. You cannot turn it into a prophecy. A pension system spreads risk across decades. It does not predict one day on a calendar.",
      sourcesCta: "See sources and methods",
      countryNames: { IT: "Italy", CH: "Switzerland", SE: "Sweden", NL: "Netherlands" },
      countryDescriptions: {
        CH: "Three pillars: a public PAYG OASI/AHV scheme, funded occupational provision above the statutory threshold and voluntary individual saving.",
        SE: "A public PAYG NDC pension, funded premium pension, public guarantee and broad occupational coverage.",
        NL: "A public PAYG AOW pension, funded occupational provision and individual products. The occupational pillar is moving towards defined contributions.",
      },
      countryLines: {
        CH: { title: "PAYG first pillar", body: "Current contributions go to current pensioners." },
        SE: { title: "Automatic balancing", body: "The balance index reduces indexation when liabilities and assets diverge." },
        NL: { title: "AOW separate from funded provision", body: "The 2023 law moves funds towards defined contributions by 2028." },
      },
      pillarLabels: {
        first_pillar: "Public first pillar",
        second_pillar: "Occupational pillar",
        third_pillar: "Voluntary personal pillar",
      },
    },
    sources: {
      kicker: "Sources and methods",
      title: "The books are open.",
      intro: "Every number above links to a source. Years and scopes remain visible because context is part of the data.",
      vocabulary: "Vocabulary",
      labelsTitle: "How to read the labels",
      labelsBody: "OBSERVED is published data. OFFICIAL PROJECTION comes from an institutional model. MODEL ESTIMATE is calculated here. SCENARIO is a controllable choice. EDITORIAL ANALOGY is language, not statistics.",
      scopes: "Scopes",
      scopesTitle: "Do not add apples and people",
      scopesBody: "Benefits, unique pensioners, category beneficiaries, INPS accounts, ESSPROS and the Ageing Report use different definitions. A figure does not become false because another source measures a different scope.",
      privacy: "Privacy",
      privacyTitle: "No data leaves the browser",
      privacyBody: "Age, salary and levers stay in the local session. The project collects no names, email addresses, tax codes or analytics events.",
      footerStart: "Local editorial project, version 0.1. Data loaded from",
      footerMiddle: "and",
      footerEnd: "The model does not calculate a collapse date.",
    },
  },
} as const;

export const getAppCopy = (language: Language) => APP_COPY[language];

export const FUNDING_LABELS: Record<Language, Record<string, string>> = {
  it: {
    PAYG: "a ripartizione",
    "PAYG mixed with NDC transition": "a ripartizione, transizione NDC",
    "PAYG NDC plus funded premium account": "NDC a ripartizione, conto finanziato",
    funded: "finanziato",
    "funded capitalisation": "capitalizzazione finanziata",
    "funded, transitioning to defined contribution": "finanziato, verso contributi definiti",
  },
  en: {
    PAYG: "PAYG",
    "PAYG mixed with NDC transition": "PAYG with NDC transition",
    "PAYG NDC plus funded premium account": "PAYG NDC plus funded premium account",
    funded: "funded",
    "funded capitalisation": "funded capitalisation",
    "funded, transitioning to defined contribution": "funded, moving to defined contribution",
  },
};

export const MANDATE_LABELS: Record<Language, Record<string, string>> = {
  it: {
    mandatory: "obbligatorio",
    "mandatory public pension": "pensione pubblica obbligatoria",
    "mandatory above statutory threshold": "obbligatorio sopra la soglia prevista",
    "broad collective-agreement or employer coverage": "copertura ampia da contratto o datore",
    "quasi-mandatory where sector or employer arrangement applies": "quasi obbligatorio dove vale un accordo",
    "compulsory social insurance for insured residents and workers": "assicurazione sociale obbligatoria per residenti e lavoratori assicurati",
    "generally voluntary": "generalmente volontario",
    voluntary: "volontario",
  },
  en: {
    mandatory: "mandatory",
    "mandatory public pension": "mandatory public pension",
    "mandatory above statutory threshold": "mandatory above the statutory threshold",
    "broad collective-agreement or employer coverage": "broad collective agreement or employer coverage",
    "quasi-mandatory where sector or employer arrangement applies": "quasi-mandatory where a sector or employer arrangement applies",
    "compulsory social insurance for insured residents and workers": "compulsory social insurance for insured residents and workers",
    "generally voluntary": "generally voluntary",
    voluntary: "voluntary",
  },
};

export const CHART_COPY = {
  it: {
    common: {
      year: "anno",
      unit: "unità",
      scope: "perimetro",
      table: "Tabella",
      unavailable: "n.d.",
    },
    timeline: {
      eyebrow: "Il tuo asse temporale",
      title: "Dal primo versamento al giorno scelto",
      aria: "Linea temporale",
      from: "da",
      to: "a",
      years: "anni",
      start: "inizio",
      today: "oggi",
      selected: "scelta",
      entered: "anni già indicati",
      future: "anni ancora nel modello",
      open: "Apri i dati della linea temporale",
      columns: { event: "Evento", age: "Età", meaning: "Lettura" },
      rows: {
        start: "Inizio",
        first: "Primo versamento indicato",
        today: "Oggi",
        pension: "Pensione simulata",
        scenario: "Scenario didattico",
      },
      source: "Modello personale locale",
      unit: "anni",
      scope: "input controllati, non estratto conto INPS",
    },
    cash: {
      eyebrow: "Conto osservato",
      title: "Entrate correnti INPS, senza trucco",
      aria: "Entrate contributive e trasferimenti correnti INPS dal 2015 al 2025",
      billion: "mld",
      contributions: "Contributi",
      total: "Entrate correnti totali",
      open: "Apri i dati osservati",
      columns: { year: "Anno", contributions: "Contributi, € mln", revenue: "Entrate correnti, € mln" },
      source: "INPS, rendiconto generale 2025",
      unit: "milioni di euro",
      scope: "entrate correnti, contributi e trasferimenti INPS",
      note: "Dati amministrativi osservati, milioni di euro, 2015-2025.",
      detail: "Le entrate correnti includono trasferimenti e altre voci. Non sono un bilancio dello Stato.",
    },
    spending: {
      eyebrow: "La traiettoria pubblicata",
      title: "Spesa pensionistica lorda sul PIL",
      aria: "Proiezione ufficiale della spesa pensionistica lorda italiana sul PIL fino al 2070",
      peak: "picco 17,3% nel 2036",
      open: "Apri i dati della proiezione",
      columns: { year: "Anno", expenditure: "Spesa lorda, % PIL", ratio: "Pensionati / occupati" },
      source: "Commissione europea, Ageing Report 2024",
      unit: "% del PIL",
      scope: "spesa pubblica lorda italiana nel baseline Ageing Report",
      note: "Baseline Ageing Report, perimetro pubblico, 2022-2070.",
      detail: "Il picco è una condizione del modello, non una data di collasso.",
    },
    demography: {
      eyebrow: "Peso demografico",
      title: "La stessa popolazione, due fotografie",
      aria: "Composizione della popolazione italiana per fasce di età nel 2024 e nel 2050",
      residents: "residenti",
      averageAge: "Età media",
      years: "anni",
      median: "2024 → 2080, scenario mediano Istat",
      open: "Apri i dati demografici",
      columns: { year: "Anno" },
      source: "Istat, previsioni della popolazione",
      yearsShown: "2024 e 2050",
      unit: "% dei residenti",
      scope: "popolazione residente per fascia d'età, scenario mediano",
      note: "Istat, scenario mediano, quote ufficiali 2024 e 2050.",
      detail: "La fascia 15-64 è un indicatore demografico, non il numero degli occupati.",
    },
    distribution: {
      eyebrow: "Distribuzione osservata",
      title: "Importo basso non significa stessa storia",
      aria: "Distribuzione delle prestazioni pensionistiche per importo mensile nel 2024",
      benefits: "prestazioni",
      amounts: "importi",
      benefitsShare: "Quota prestazioni",
      amountsShare: "Quota importi",
      open: "Apri la distribuzione in tabella",
      columns: { band: "Fascia mensile", benefits: "Quota prestazioni", amounts: "Quota importi" },
      source: "INPS, osservatorio beneficiari 2024",
      unit: "% di prestazioni e importi annualizzati",
      scope: "prestazioni pensionistiche per fascia mensile, non persone uniche",
      note: "INPS, beneficiari 2024, importi annualizzati in milioni di euro.",
      detail: "Una prestazione non è una persona. Le bande non provano né povertà né abuso.",
    },
    multiple: {
      eyebrow: "Combinazioni",
      title: "Più prestazioni, non automaticamente un abuso",
      aria: "Quota di pensionati con una sola categoria o con più categorie di prestazione",
      combined: "cumulano",
      single: "Solo tipo",
      withOther: "Con almeno un altro tipo",
      open: "Apri le combinazioni in tabella",
      columns: { category: "Categoria", single: "Solo tipo", combined: "Con altri tipi" },
      source: "INPS, osservatorio beneficiari 2024",
      unit: "% di categorie di beneficiari",
      scope: "categorie sovrapposte, una persona può comparire più volte",
      note: "INPS, osservatorio beneficiari al 31 dicembre 2024.",
      detail: "Le righe si sovrappongono: una persona può comparire in più categorie.",
      categories: {
        "old-age": "vecchiaia",
        "contributory invalidity": "invalidità contributiva",
        survivor: "superstiti",
        indennitarie: "indennitarie",
        assistenziale: "assistenziale",
      },
    },
    macro: {
      eyebrow: "La leva che scegli",
      title: "Pressione, aliquota e prestazione nello stesso foglio",
      aria: "Grafico del modello macro con pressione, aliquota PAYG necessaria e sostituzione media proxy",
      low: "Scenario basso",
      central: "Scenario centrale",
      high: "Scenario alto",
      rate: "Aliquota necessaria / 20",
      replacement: "Sostituzione media proxy",
      open: "Apri i risultati macro in tabella",
      columns: { year: "Anno", pressure: "Pressione", workers: "Occupati / beneficiario", rate: "Aliquota necessaria", balance: "Bilancio proxy", replacement: "Sostituzione proxy" },
      source: "Modello macro locale",
      unit: "indici, percentuali e rapporti",
      scope: "proxy di flusso, non bilancio pubblico",
      note: "Stima del modello, base 2025, valori indicizzati.",
      detail: "La linea gialla è divisa per 20 per stare nello stesso riquadro. Non è un bilancio INPS, né una previsione di contabilità pubblica.",
    },
    international: {
      eyebrow: "Confronto armonizzato",
      aria: "confronto tra Italia, Svizzera, Svezia e Paesi Bassi",
      open: "Apri il confronto in tabella",
      columns: { country: "Paese", value: "Valore" },
      fallbackSource: "Fonte comparativa",
      missingYear: "non indicato",
      missingUnit: "non indicata",
      fallbackScope: "quattro paesi, definizione indicata dalla fonte",
      comparability: "comparabilità",
      high: "alta",
      medium: "media",
      low: "bassa",
      fallbackNote: "La definizione è quella indicata dalla fonte.",
      countries: { IT: "Italia", CH: "Svizzera", SE: "Svezia", NL: "Paesi Bassi" },
      metricLabels: {
        public_pension_expenditure_gdp: "Spesa pubblica per pensioni sul PIL",
        pension_provider_assets_gdp: "Attività dei gestori pensionistici sul PIL",
        mandatory_effective_contribution_rate: "Aliquota contributiva obbligatoria effettiva",
        old_age_dependency_ratio: "Indice di dipendenza degli anziani",
      },
      metricNotes: {
        public_pension_expenditure_gdp: "La definizione OECD copre le prestazioni pubbliche in denaro per vecchiaia e superstiti.",
        pension_provider_assets_gdp: "Sono attività di schemi finanziati. Non rappresentano il valore delle promesse PAYG.",
        mandatory_effective_contribution_rate: "Le aliquote sono armonizzate da OECD, ma i perimetri dei sistemi restano diversi.",
        old_age_dependency_ratio: "È il rapporto tra popolazione di 65 anni e oltre e popolazione tra 15 e 64 anni.",
      },
    },
  },
  en: {
    common: {
      year: "year",
      unit: "unit",
      scope: "scope",
      table: "Table",
      unavailable: "n/a",
    },
    timeline: {
      eyebrow: "Your timeline",
      title: "From the first contribution to the selected date",
      aria: "Timeline",
      from: "from",
      to: "to",
      years: "years",
      start: "start",
      today: "today",
      selected: "selected",
      entered: "years entered so far",
      future: "years still inside the model",
      open: "Open timeline data",
      columns: { event: "Event", age: "Age", meaning: "Meaning" },
      rows: {
        start: "Start",
        first: "First contribution entered",
        today: "Today",
        pension: "Simulated pension",
        scenario: "Teaching scenario",
      },
      source: "Local personal model",
      unit: "years",
      scope: "controlled inputs, not an INPS statement",
    },
    cash: {
      eyebrow: "Observed account",
      title: "INPS current revenue, without sleight of hand",
      aria: "INPS contribution revenue and current transfers from 2015 to 2025",
      billion: "bn",
      contributions: "Contributions",
      total: "Total current revenue",
      open: "Open observed data",
      columns: { year: "Year", contributions: "Contributions, €m", revenue: "Current revenue, €m" },
      source: "INPS, 2025 general accounts",
      unit: "millions of euros",
      scope: "INPS current revenue, contributions and transfers",
      note: "Observed administrative data, millions of euros, 2015-2025.",
      detail: "Current revenue includes transfers and other items. It is not the state budget.",
    },
    spending: {
      eyebrow: "The published path",
      title: "Gross pension spending as a share of GDP",
      aria: "Official projection of Italian gross pension spending as a share of GDP through 2070",
      peak: "17.3% peak in 2036",
      open: "Open projection data",
      columns: { year: "Year", expenditure: "Gross spending, % GDP", ratio: "Pensioners / workers" },
      source: "European Commission, 2024 Ageing Report",
      unit: "% of GDP",
      scope: "Italian gross public spending in the Ageing Report baseline",
      note: "Ageing Report baseline, public scope, 2022-2070.",
      detail: "The peak is conditional on the model. It is not a collapse date.",
    },
    demography: {
      eyebrow: "Demographic weight",
      title: "The same population, two snapshots",
      aria: "Italian population by age group in 2024 and 2050",
      residents: "residents",
      averageAge: "Average age",
      years: "years",
      median: "2024 → 2080, Istat median scenario",
      open: "Open demographic data",
      columns: { year: "Year" },
      source: "Istat, population projections",
      yearsShown: "2024 and 2050",
      unit: "% of residents",
      scope: "resident population by age group, median scenario",
      note: "Istat median scenario, official shares for 2024 and 2050.",
      detail: "The 15-64 group is a demographic measure, not the number of people in work.",
    },
    distribution: {
      eyebrow: "Observed distribution",
      title: "A low amount does not imply the same history",
      aria: "Distribution of pension benefits by monthly amount in 2024",
      benefits: "benefits",
      amounts: "amounts",
      benefitsShare: "Share of benefits",
      amountsShare: "Share of amounts",
      open: "Open distribution table",
      columns: { band: "Monthly band", benefits: "Share of benefits", amounts: "Share of amounts" },
      source: "INPS, 2024 beneficiary observatory",
      unit: "% of benefits and annualised amounts",
      scope: "pension benefits by monthly band, not unique people",
      note: "INPS, 2024 beneficiaries, annualised amounts in millions of euros.",
      detail: "A benefit is not a person. The bands prove neither poverty nor abuse.",
    },
    multiple: {
      eyebrow: "Combinations",
      title: "Multiple benefits do not automatically mean abuse",
      aria: "Share of pensioners with one benefit category or several benefit categories",
      combined: "combine",
      single: "One category only",
      withOther: "With at least one other category",
      open: "Open combinations table",
      columns: { category: "Category", single: "One category only", combined: "With other categories" },
      source: "INPS, 2024 beneficiary observatory",
      unit: "% of beneficiary categories",
      scope: "overlapping categories, one person may appear more than once",
      note: "INPS beneficiary observatory at 31 December 2024.",
      detail: "Rows overlap. One person can appear in several categories.",
      categories: {
        "old-age": "old-age",
        "contributory invalidity": "contributory invalidity",
        survivor: "survivor",
        indennitarie: "employment injury",
        assistenziale: "social assistance",
      },
    },
    macro: {
      eyebrow: "Your selected lever",
      title: "Pressure, rate and benefit on the same sheet",
      aria: "Macro model chart with pressure, required PAYG rate and average replacement proxy",
      low: "Low scenario",
      central: "Central scenario",
      high: "High scenario",
      rate: "Required rate / 20",
      replacement: "Average replacement proxy",
      open: "Open macro results table",
      columns: { year: "Year", pressure: "Pressure", workers: "Workers / beneficiary", rate: "Required rate", balance: "Balance proxy", replacement: "Replacement proxy" },
      source: "Local macro model",
      unit: "indices, percentages and ratios",
      scope: "flow proxy, not public accounts",
      note: "Model estimate, 2025 base, indexed values.",
      detail: "The yellow line is divided by 20 to fit the same plot. It is not an INPS account or a public finance forecast.",
    },
    international: {
      eyebrow: "Harmonised comparison",
      aria: "comparison across Italy, Switzerland, Sweden and the Netherlands",
      open: "Open comparison table",
      columns: { country: "Country", value: "Value" },
      fallbackSource: "Comparative source",
      missingYear: "not stated",
      missingUnit: "not stated",
      fallbackScope: "four countries, definition stated by the source",
      comparability: "comparability",
      high: "high",
      medium: "medium",
      low: "low",
      fallbackNote: "The definition follows the cited source.",
      countries: { IT: "Italy", CH: "Switzerland", SE: "Sweden", NL: "Netherlands" },
      metricLabels: {
        public_pension_expenditure_gdp: "Public pension spending as a share of GDP",
        pension_provider_assets_gdp: "Pension provider assets as a share of GDP",
        mandatory_effective_contribution_rate: "Effective mandatory contribution rate",
        old_age_dependency_ratio: "Old-age dependency ratio",
      },
      metricNotes: {
        public_pension_expenditure_gdp: "The OECD definition covers public cash benefits for old age and survivors.",
        pension_provider_assets_gdp: "These are assets in funded arrangements. They do not value PAYG promises.",
        mandatory_effective_contribution_rate: "The OECD harmonises the rates, but national system scopes still differ.",
        old_age_dependency_ratio: "This is the ratio of residents aged 65 or over to residents aged 15 to 64.",
      },
    },
  },
} as const;

export const getChartCopy = (language: Language) => CHART_COPY[language];
