import type { Language } from "./language";

export const STORY_COPY = {
  it: {
    common: {
      brand: "ITALIAN DEATH CLOCK",
      skip: "Vai al contenuto",
      language: "Cambia lingua",
      source: "Fonte",
      openSource: "Apri la fonte primaria",
      observed: "FATTO OSSERVATO",
      official: "PROIEZIONE UFFICIALE",
      scenario: "SCENARIO DIDATTICO",
      method: "Metodo e fonti",
      loading: "Carico i dati pubblici…",
      failed: "I dati pubblici non sono disponibili.",
      retry: "Riprova",
      days: "giorni",
      hours: "ore",
      minutes: "minuti",
      seconds: "secondi",
      scroll: "Scorri per capire il conto",
      external: "si apre in una nuova scheda",
    },
    hero: {
      eyebrow: "TEMPO ALL’ANNO DI PICCO PREVISTO",
      title: "Non è la data del collasso.",
      titleAccent: "è il picco del conto.",
      body: "Nel 2036 la spesa pensionistica pubblica è proiettata al 17,3% del PIL. Il timer usa il 1° gennaio come riferimento visivo: la fonte indica l’anno, non un giorno esatto.",
      metric: "17,3% DEL PIL",
      metricLabel: "spesa pensionistica pubblica lorda al picco previsto",
      screenReaderCountdown: "Meno di dieci anni all’anno 2036, anno del picco previsto della spesa pensionistica pubblica.",
    },
    payg: {
      kicker: "COME FUNZIONA",
      title: "I contributi di oggi non aspettano te.",
      accent: "Pagano le pensioni di oggi.",
      body: "Il sistema pubblico italiano è a ripartizione. Le entrate contributive e i trasferimenti dello Stato finanziano le prestazioni correnti. Non esiste un conto personale pieno dei tuoi versamenti.",
      fact: "33%",
      factLabel: "aliquota pensionistica di riferimento per i dipendenti",
      note: "Una parte è a carico del lavoratore, una parte del datore di lavoro.",
      alt: "Tre lavoratori passano un flusso di contributi a una pensionata, illustrazione del sistema a ripartizione.",
    },
    demography: {
      kicker: "IL PESO CAMBIA",
      title: "La base si restringe.",
      accent: "Il carico aumenta.",
      body: "Nel 2050 la quota di residenti tra 15 e 64 anni è prevista in calo, mentre la quota con almeno 65 anni cresce. Non sono conteggi di lavoratori e pensionati, ma mostrano la direzione demografica.",
      working: "15–64 anni",
      older: "65 anni o più",
      now: "2024",
      future: "2050",
      workingNow: "63,5%",
      workingFuture: "54,3%",
      olderNow: "24,3%",
      olderFuture: "34,6%",
      alt: "Una grande folla su una piattaforma sostenuta da tre figure, metafora del peso demografico.",
    },
    spending: {
      kicker: "IL CONTO PUBBLICO",
      title: "Sale. Tocca il picco.",
      accent: "Poi scende, ma non gratis.",
      body: "La proiezione ufficiale non descrive un’esplosione senza fine. Dopo il 2036 la quota di PIL diminuisce anche perché cambiano età di uscita e rapporto tra prima pensione e ultimo reddito.",
      y2022: "2022",
      y2036: "2036",
      y2070: "2070",
      v2022: "15,6%",
      v2036: "17,3%",
      v2070: "13,7%",
      unit: "del PIL",
      chartAlt: "La spesa pensionistica pubblica lorda sale dal 15,6% del PIL nel 2022 al picco previsto del 17,3% nel 2036, poi scende al 13,7% nel 2070.",
    },
    personal: {
      kicker: "IL NUMERO CHE INGANNAVA",
      title: "Un euro futuro non è un euro di oggi.",
      body: "La vecchia simulazione mescolava una scorciatoia di calcolo con un importo poco spiegato. Qui usiamo il tasso lordo di sostituzione ufficiale come esempio, non come previsione INPS personale.",
      age: "La tua età oggi",
      salary: "Retribuzione lorda annua di oggi",
      retirement: "Anno illustrativo di pensionamento",
      replacement: "Tasso lordo di sostituzione proiettato",
      realTitle: "Potere d’acquisto di oggi",
      realNote: "per rata lorda, 13 rate, in euro 2026",
      nominalTitle: "Importo scritto sul cedolino futuro",
      nominalNote: "per rata lorda, con inflazione media ipotetica del 2%",
      equal: "I due importi hanno lo stesso potere d’acquisto nello scenario.",
      assumptions: "Carriera e retribuzione reale costanti, uscita a 67 anni, 13 rate. Il 2% è uno scenario, non una previsione dell’inflazione. Il risultato non è la tua pensione INPS.",
      inflation: "2% inflazione media ipotetica",
      payments: "13 rate",
      gross: "lordi",
    },
    levers: {
      kicker: "NON ESISTE UN SOLO INTERRUTTORE",
      title: "Il conto si sposta.",
      accent: "Non scompare.",
      intro: "Ogni scelta distribuisce il peso tra generazioni. Le leve sono poche e hanno conseguenze diverse.",
      items: [
        { number: "01", title: "Più persone al lavoro", body: "Occupazione, carriere continue e migrazione ampliano la base contributiva." },
        { number: "02", title: "Più valore per lavoratore", body: "Produttività e salari reali aumentano le risorse su cui si versano contributi." },
        { number: "03", title: "Regole diverse", body: "Età, aliquote, trasferimenti e prestazioni cambiano chi paga, quando e quanto." },
      ],
      note: "Queste sono leve contabili, non raccomandazioni politiche.",
    },
    closing: {
      title: "Il sistema non finisce in un giorno.",
      accent: "Sposta il peso su chi lavora domani.",
      body: "Il vero conto alla rovescia non porta a una data certa. Misura il tempo disponibile per decidere come distribuire quel peso.",
      sourcesIntro: "Ogni numero della storia viene dal pack pubblico del progetto. Le proiezioni dipendono da regole e ipotesi che possono cambiare.",
      sourceList: "Fonti principali",
      privacy: "Nessun dato personale viene inviato o salvato. I due controlli restano nel browser.",
    },
  },
  en: {
    common: {
      brand: "ITALIAN DEATH CLOCK",
      skip: "Skip to content",
      language: "Change language",
      source: "Source",
      openSource: "Open the primary source",
      observed: "OBSERVED FACT",
      official: "OFFICIAL PROJECTION",
      scenario: "TEACHING SCENARIO",
      method: "Method and sources",
      loading: "Loading public data…",
      failed: "Public data is unavailable.",
      retry: "Try again",
      days: "days",
      hours: "hours",
      minutes: "minutes",
      seconds: "seconds",
      scroll: "Scroll to understand the bill",
      external: "opens in a new tab",
    },
    hero: {
      eyebrow: "TIME TO THE PROJECTED PEAK YEAR",
      title: "This is not a collapse date.",
      titleAccent: "It is the peak of the bill.",
      body: "In 2036, gross public pension spending is projected to reach 17.3% of GDP. The timer uses 1 January as a visual anchor: the source gives a year, not an exact day.",
      metric: "17.3% OF GDP",
      metricLabel: "gross public pension spending at the projected peak",
      screenReaderCountdown: "Less than ten years to 2036, the projected peak year for public pension spending.",
    },
    payg: {
      kicker: "HOW IT WORKS",
      title: "Today’s contributions do not wait for you.",
      accent: "They pay today’s pensions.",
      body: "Italy’s public system is pay as you go. Contribution revenue and state transfers finance current benefits. There is no fully funded personal account holding your contributions.",
      fact: "33%",
      factLabel: "reference pension contribution rate for employees",
      note: "One share is paid by the worker and one by the employer.",
      alt: "Three workers pass a stream of contributions to a retired woman, illustrating a pay-as-you-go system.",
    },
    demography: {
      kicker: "THE WEIGHT SHIFTS",
      title: "The base narrows.",
      accent: "The load grows.",
      body: "By 2050, the share of residents aged 15 to 64 is projected to fall while the share aged 65 or over rises. These are not worker and pensioner counts, but they show the demographic direction.",
      working: "Age 15–64",
      older: "Age 65 or over",
      now: "2024",
      future: "2050",
      workingNow: "63.5%",
      workingFuture: "54.3%",
      olderNow: "24.3%",
      olderFuture: "34.6%",
      alt: "A large crowd on a platform held up by three figures, a metaphor for demographic weight.",
    },
    spending: {
      kicker: "THE PUBLIC BILL",
      title: "It rises. It peaks.",
      accent: "Then it falls, but not for free.",
      body: "The official projection does not show spending rising forever. After 2036, the GDP share falls partly because exit ages and the ratio between first pension and final income also change.",
      y2022: "2022",
      y2036: "2036",
      y2070: "2070",
      v2022: "15.6%",
      v2036: "17.3%",
      v2070: "13.7%",
      unit: "of GDP",
      chartAlt: "Gross public pension spending rises from 15.6% of GDP in 2022 to a projected peak of 17.3% in 2036, then falls to 13.7% in 2070.",
    },
    personal: {
      kicker: "THE NUMBER THAT MISLED",
      title: "A future euro is not today’s euro.",
      body: "The old simulation mixed a calculation shortcut with a poorly explained amount. Here we use the official projected gross replacement rate as an example, not as a personal INPS forecast.",
      age: "Your age today",
      salary: "Today’s gross annual pay",
      retirement: "Illustrative retirement year",
      replacement: "Projected gross replacement rate",
      realTitle: "Today’s purchasing power",
      realNote: "per gross payment, 13 payments, in 2026 euros",
      nominalTitle: "Face value on the future payslip",
      nominalNote: "per gross payment, assuming 2% average inflation",
      equal: "Both amounts have the same purchasing power in this scenario.",
      assumptions: "Continuous career and constant real pay, retirement at 67, 13 payments. The 2% rate is a scenario, not an inflation forecast. This result is not your INPS pension.",
      inflation: "2% assumed average inflation",
      payments: "13 payments",
      gross: "gross",
    },
    levers: {
      kicker: "THERE IS NO SINGLE SWITCH",
      title: "The bill moves.",
      accent: "It does not disappear.",
      intro: "Every choice distributes weight between generations. The levers are few and their consequences differ.",
      items: [
        { number: "01", title: "More people at work", body: "Employment, continuous careers and migration widen the contribution base." },
        { number: "02", title: "More value per worker", body: "Productivity and real wages increase the resources on which contributions are paid." },
        { number: "03", title: "Different rules", body: "Ages, rates, transfers and benefits change who pays, when and how much." },
      ],
      note: "These are accounting levers, not policy recommendations.",
    },
    closing: {
      title: "The system does not end in one day.",
      accent: "It shifts weight onto tomorrow’s workers.",
      body: "The real countdown does not lead to a certain date. It measures the time available to decide how that weight will be shared.",
      sourcesIntro: "Every number in the story comes from the project’s public data pack. Projections depend on rules and assumptions that can change.",
      sourceList: "Primary sources",
      privacy: "No personal data is sent or stored. Both controls stay in the browser.",
    },
  },
} as const;

export const getStoryCopy = (language: Language) => STORY_COPY[language];
