import type { Language } from "./language";

export const STORY_COPY = {
  it: {
    common: {
      brand: "ITALIAN DEATH CLOCK",
      skip: "Vai al contenuto",
      language: "Cambia lingua",
      source: "Fonte",
      openSource: "Apri la fonte primaria",
      observed: "FATTO OSSERVATO",
      official: "PROIEZIONE UFFICIALE",
      scenario: "SCENARIO DIDATTICO",
      method: "Metodo e fonti",
      loading: "Carico i dati pubblici...",
      failed: "I dati pubblici non sono disponibili.",
      retry: "Riprova",
      days: "giorni",
      hours: "ore",
      minutes: "minuti",
      seconds: "secondi",
      scroll: "Scorri per capire il conto",
      external: "si apre in una nuova scheda",
    },
    hero: {
      eyebrow: "IL PICCO È UNA PROIEZIONE, NON UNA SCADENZA",
      title: "Il sistema non collassa in un giorno.",
      titleAccent: "Il conto si accumula ogni giorno.",
      body: "La baseline dell'Ageing Report 2024 porta la spesa pensionistica pubblica lorda al 17,3% del PIL nel 2036, dal 15,6% del 2022. È un percorso condizionato da regole e ipotesi, non una data di collasso. Il timer usa il 1 gennaio solo per rendere visibile l'anno di picco.",
      timerNote: "Il 1 gennaio è un'ancora visiva. La fonte indica il 2036, non un giorno preciso.",
      metric: "17,3% DEL PIL",
      metricLabel: "spesa pensionistica pubblica lorda al picco previsto",
      screenReaderCountdown: "Meno di dieci anni al 2036, anno del picco previsto della spesa pensionistica pubblica.",
    },
    payg: {
      kicker: "PRIMO FATTO: I CONTRIBUTI NON RESTANO IN CASSAFORTE",
      title: "Il versamento di oggi",
      accent: "paga una pensione oggi.",
      body: "L'Italia ha un sistema pubblico obbligatorio a ripartizione. I contributi correnti finanziano le prestazioni correnti insieme ai trasferimenti dal bilancio dello Stato. Quel trasferimento è spesa pubblica, non un contributo personale: passa dal bilancio generale, alimentato da imposte e debito, e il rendiconto mostra la linea di trasferimento, non una singola imposta. La riforma contributiva calcola un diritto sui versamenti e sulla crescita nominale del PIL, ma non trasforma l'INPS in un conto investito a tuo nome. Fonte: Ageing Report 2024 e Rendiconto INPS 2025.",
      fact: "33%",
      factLabel: "aliquota pensionistica di riferimento per i dipendenti, 2023",
      note: "Per i dipendenti, circa un terzo è a carico del lavoratore e due terzi del datore. Altre categorie hanno aliquote diverse.",
      flow: ["Contributi di lavoratori e datori", "Trasferimenti dello Stato", "Pensioni correnti"],
      alt: "Contributi di lavoratori e datori e trasferimenti dello Stato alimentano le pensioni correnti in un sistema a ripartizione.",
    },
    demography: {
      kicker: "IL PESO CAMBIA",
      title: "Meno giovani entrano.",
      accent: "Più anziani restano.",
      body: "L'ultima lettura Istat registra, in via provvisoria, 355 mila nascite nel 2025 e 1,14 figli per donna. Nello scenario mediano Istat con base 1/1/2024, la quota dei residenti tra 15 e 64 anni scende dal 63,5% del 2024 al 54,3% nel 2050, mentre quella dei residenti con almeno 65 anni sale dal 24,3% al 34,6%. Sono quote di residenti per età, non conteggi di lavoratori e pensionati.",
      working: "15-64 anni",
      older: "65 anni o più",
      now: "2024",
      future: "2050",
      workingNow: "63,5%",
      workingFuture: "54,3%",
      olderNow: "24,3%",
      olderFuture: "34,6%",
      alt: "Una grande folla su una piattaforma sostenuta da tre figure, metafora del peso demografico.",
    },
    spending: {
      kicker: "IL CONTO PUBBLICO",
      title: "La curva sale.",
      accent: "La curva scende. Il conto resta.",
      body: "La baseline dell'Ageing Report 2024 porta la spesa lorda dal 15,6% del PIL nel 2022 al 17,3% nel 2036 e al 13,7% nel 2070. La discesa è il risultato del percorso ipotizzato dal modello, tra età di uscita, rapporto tra prima pensione e reddito finale, demografia e crescita. Non dimostra che il problema si risolva da solo.",
      y2022: "2022",
      y2036: "2036",
      y2070: "2070",
      v2022: "15,6%",
      v2036: "17,3%",
      v2070: "13,7%",
      unit: "del PIL",
      chartAlt: "La spesa pensionistica pubblica lorda sale dal 15,6% del PIL nel 2022 al picco previsto del 17,3% nel 2036, poi scende al 13,7% nel 2070.",
    },
    personal: {
      kicker: "LA TUA STIMA",
      title: "Quanto potresti ricevere. Quanto varrebbe.",
      body: "Inserisci età, retribuzione lorda, contributi già maturati e inflazione. Stimiamo prima la rata lorda futura, poi la traduciamo nel potere d'acquisto del 2026.",
      age: "La tua età oggi",
      contributions: "Anni di contributi maturati",
      salary: "Retribuzione lorda annua di oggi",
      inflation: "Inflazione media annua",
      retirement: "Anno nello scenario, uscita a 67 anni",
      contributionsAtRetirement: "Contributi stimati a 67 anni",
      replacement: "Quota lorda stimata della retribuzione",
      nominalTitle: "Pensione lorda stimata",
      nominalNote: (year: number) => `per rata nel ${year}, 13 rate`,
      realTitle: "Vale in euro di oggi",
      realNote: "stesso potere d'acquisto, in euro 2026",
      equivalence: ({ futureAmount, currentAmount, retirementYear, years, inflationPercent }: { futureAmount: string; currentAmount: string; retirementYear: number; years: number; inflationPercent: string }) =>
        `Con un'inflazione media del ${inflationPercent}% per ${years} anni, ${futureAmount} nel ${retirementYear} avrebbe lo stesso potere d'acquisto di ${currentAmount} nel 2026.`,
      eligibility: ({ projectedYears, minimumYears }: { projectedYears: string; minimumYears: number }) =>
        `Con ${projectedYears} anni di contributi stimati a 67 anni non raggiungeresti il requisito ordinario attuale di ${minimumYears} anni. Per questo non mostriamo un importo. Altre vie di pensionamento hanno requisiti diversi.`,
      assumptions: "Stima didattica lorda: lavoro continuo fino a 67 anni, retribuzione reale costante e 13 rate. Il tasso ufficiale medio è adeguato in proporzione agli anni contributivi rispetto alla carriera media proiettata. I 20 anni sono solo il minimo ordinario attuale e possono valere altri requisiti. L'inflazione scelta è uno scenario, non una previsione. Imposte, regole dei fondi e posizione INPS individuale non sono incluse.",
      years: "anni",
    },
    levers: {
      kicker: "LE RIFORME SPOSTANO IL PESO",
      title: "Non c'è un interruttore.",
      accent: "C'è un conto da dividere.",
      intro: "Puoi allargare la base, far crescere il reddito, cambiare età e regole o finanziare una quota con risorse di bilancio. Ogni leva riduce una pressione e ne crea un'altra. Una riforma finanziata spostando contributi verso fondi investiti deve continuare a pagare i diritti maturati nella ripartizione.",
      items: [
        { number: "01", title: "Più persone con un lavoro", body: "Occupazione, carriere meno interrotte e migrazione allargano la base contributiva. L'effetto dipende da quanti lavorano, da quanto guadagnano e da quanto a lungo restano al lavoro." },
        { number: "02", title: "Più valore per ogni ora", body: "Il modello Ageing Report 2024 usa una crescita della produttività come ipotesi. Nella sensibilità più debole, la spesa lorda sale di circa 0,6 punti di PIL rispetto alla baseline intorno al 2060. La crescita è un input, non un assegno." },
        { number: "03", title: "Regole diverse, costi visibili", body: "Età, aliquote, indicizzazione, trasferimenti e prestazioni cambiano chi paga, quando e quanto. L'Osservatorio INPS su prestazioni e beneficiari, con riferimento al 31 dicembre 2024, rileva che il 31,9% dei beneficiari riceve due o più prestazioni e che l'1,6% delle prestazioni vale almeno 5.000 euro lordi al mese. Sono categorie amministrative, non prove di abuso." },
      ],
      note: "OECD Pensions Outlook 2022: spostare contributi dalla ripartizione a fondi investiti lascia da finanziare i diritti già maturati. Nel passaggio qualcuno può pagare due volte, con più imposte, altro debito, tagli alla spesa o prestazioni più basse. Queste sono leve contabili, non raccomandazioni politiche.",
    },
    closing: {
      title: "Non c'è una data di fine.",
      accent: "C'è una scelta di chi paga.",
      body: "Il rischio non è un'esplosione in un giorno. È una promessa che diventa più costosa quando diminuiscono i contribuenti e aumentano i beneficiari. Nel bilancio INPS 2025 risultano 294.194 milioni di euro di entrate contributive, 165.419 milioni di trasferimenti dallo Stato e 325.067 milioni di uscite pensionistiche INPS. Sono conti di competenza con perimetri diversi, non il saldo di tutto lo Stato e non una prova che ogni pensione sia finanziata solo dai contributi.",
      sourcesIntro: "I numeri osservati vengono dai bilanci e dagli osservatori INPS. Le proiezioni vengono dall'Ageing Report della Commissione europea con MEF e RGS e dalle previsioni Istat. Ogni proiezione dipende da regole, natalità, migrazione, occupazione, produttività, inflazione e longevità.",
      sourceList: "Fonti primarie e perimetri",
      sourceLinks: [
        { label: "Commissione europea, MEF e RGS, Ageing Report 2024, scheda Italia", year: "2024", url: "https://economy-finance.ec.europa.eu/document/download/82b762d7-21ce-4992-aa97-888fd2c66205_en?filename=2024-ageing-report-country-fiche-Italy.pdf" },
        { label: "Istat, Indicatori demografici 2025, nascite e fecondità provvisorie", year: "2026", url: "https://www.istat.it/comunicato-stampa/indicatori-demografici-anno-2025/" },
        { label: "Istat, previsioni della popolazione e delle famiglie, base 1/1/2024", year: "2025", url: "https://www.istat.it/comunicato-stampa/previsioni-della-popolazione-residente-e-delle-famiglie-base-1-1-2024/" },
        { label: "INPS, Rendiconto generale 2025", year: "2026", url: "https://www.inps.it/content/dam/inps-site/pdf/allegatinews/Relazione_rendiconto_generale_2025.pdf" },
        { label: "INPS, pensioni e beneficiari al 31 dicembre 2024", year: "2025", url: "https://servizi2.inps.it/servizi/osservatoristatistici/api/getAllegato/?idAllegato=1007" },
        { label: "OECD, Pensions at a Glance 2025, Italia", year: "2025", url: "https://www.oecd.org/en/publications/pensions-at-a-glance-2025-country-notes_8a53ef12-en/italy_3dd0d4fa-en.html" },
        { label: "OECD, Pensions Outlook 2022, costi della transizione ai fondi", year: "2022", url: "https://www.oecd.org/en/publications/oecd-pensions-outlook-2022_20c7f443-en/full-report/component-4.html" },
      ],
      privacy: "Nessun dato personale viene inviato o salvato. I quattro controlli restano nel browser.",
    },
  },
  en: {
    common: {
      brand: "ITALIAN DEATH CLOCK",
      skip: "Skip to content",
      language: "Change language",
      source: "Source",
      openSource: "Open the primary source",
      observed: "OBSERVED FACT",
      official: "OFFICIAL PROJECTION",
      scenario: "TEACHING SCENARIO",
      method: "Method and sources",
      loading: "Loading public data...",
      failed: "Public data is unavailable.",
      retry: "Try again",
      days: "days",
      hours: "hours",
      minutes: "minutes",
      seconds: "seconds",
      scroll: "Scroll to understand the bill",
      external: "opens in a new tab",
    },
    hero: {
      eyebrow: "THE PEAK IS A PROJECTION, NOT A DEADLINE",
      title: "The system does not collapse in one day.",
      titleAccent: "The bill builds every day.",
      body: "The 2024 Ageing Report baseline puts gross public pension spending at 17.3% of GDP in 2036, up from 15.6% in 2022. That is a path shaped by rules and assumptions, not a collapse date. The timer uses 1 January only to make the peak year visible.",
      timerNote: "1 January is a visual anchor. The source gives 2036, not an exact day.",
      metric: "17.3% OF GDP",
      metricLabel: "gross public pension spending at the projected peak",
      screenReaderCountdown: "Less than ten years to 2036, the projected peak year for public pension spending.",
    },
    payg: {
      kicker: "FIRST FACT: CONTRIBUTIONS DO NOT SIT IN A VAULT",
      title: "Today's payment",
      accent: "pays today's pension.",
      body: "Italy has a mandatory public pay-as-you-go system. Current contributions finance current benefits alongside transfers from the state budget. That transfer is public spending, not a personal contribution: it runs through the general budget, funded by taxes and borrowing, and the accounts show the transfer line rather than one tax assigned to one pension. The contributory reform builds a right from contributions and nominal GDP growth, but it does not turn INPS into an investment account in your name. Source: 2024 Ageing Report and INPS General Accounts 2025.",
      fact: "33%",
      factLabel: "reference pension contribution rate for employees, 2023",
      note: "For employees, about one third is paid by the worker and two thirds by the employer. Other groups have different rates.",
      flow: ["Worker and employer contributions", "State transfers", "Current pensions"],
      alt: "Worker and employer contributions and state transfers feed current pensions in a pay-as-you-go system.",
    },
    demography: {
      kicker: "THE WEIGHT SHIFTS",
      title: "Fewer young people enter.",
      accent: "More older people remain.",
      body: "The latest Istat reading provisionally records 355,000 births in 2025 and 1.14 children per woman. In Istat's median scenario based on 1 January 2024, the share of residents aged 15 to 64 falls from 63.5% in 2024 to 54.3% in 2050, while the share aged 65 or over rises from 24.3% to 34.6%. These are resident age shares, not counts of workers and pensioners.",
      working: "Age 15-64",
      older: "Age 65 or over",
      now: "2024",
      future: "2050",
      workingNow: "63.5%",
      workingFuture: "54.3%",
      olderNow: "24.3%",
      olderFuture: "34.6%",
      alt: "A large crowd on a platform held up by three figures, a metaphor for demographic weight.",
    },
    spending: {
      kicker: "THE PUBLIC BILL",
      title: "The curve rises.",
      accent: "The curve falls. The bill stays.",
      body: "The 2024 Ageing Report baseline takes gross spending from 15.6% of GDP in 2022 to 17.3% in 2036 and 13.7% in 2070. The decline follows the model's assumed path for exit ages, the ratio between a first pension and final income, demography and growth. It does not show that the problem solves itself.",
      y2022: "2022",
      y2036: "2036",
      y2070: "2070",
      v2022: "15.6%",
      v2036: "17.3%",
      v2070: "13.7%",
      unit: "of GDP",
      chartAlt: "Gross public pension spending rises from 15.6% of GDP in 2022 to a projected peak of 17.3% in 2036, then falls to 13.7% in 2070.",
    },
    personal: {
      kicker: "YOUR ESTIMATE",
      title: "What you might receive. What it would be worth.",
      body: "Enter your age, gross pay, accrued contribution years and inflation. We first estimate the future gross payment, then translate it into 2026 purchasing power.",
      age: "Your age today",
      contributions: "Contribution years accrued",
      salary: "Today's gross annual pay",
      inflation: "Average annual inflation",
      retirement: "Scenario year, retirement at 67",
      contributionsAtRetirement: "Projected contributions at 67",
      replacement: "Estimated gross share of pay",
      nominalTitle: "Estimated gross pension",
      nominalNote: (year: number) => `per payment in ${year}, 13 payments`,
      realTitle: "Worth in today's euros",
      realNote: "same purchasing power, in 2026 euros",
      equivalence: ({ futureAmount, currentAmount, retirementYear, years, inflationPercent }: { futureAmount: string; currentAmount: string; retirementYear: number; years: number; inflationPercent: string }) =>
        `With ${inflationPercent}% average inflation for ${years} years, ${futureAmount} in ${retirementYear} would have the same purchasing power as ${currentAmount} in 2026.`,
      eligibility: ({ projectedYears, minimumYears }: { projectedYears: string; minimumYears: number }) =>
        `With ${projectedYears} projected contribution years at age 67, you would not meet the current ordinary requirement of ${minimumYears} years. No amount is shown. Other retirement routes have different requirements.`,
      assumptions: "Gross teaching estimate: continuous work to age 67, constant real pay and 13 payments. The official average rate is adjusted in proportion to your contribution years against the projected average career. Twenty years is only the current ordinary minimum and other requirements may apply. Selected inflation is a scenario, not a forecast. Taxes, fund rules and your individual INPS record are not included.",
      years: "years",
    },
    levers: {
      kicker: "REFORMS MOVE THE WEIGHT",
      title: "There is no single switch.",
      accent: "There is a bill to divide.",
      intro: "You can widen the base, grow incomes, change ages and rules, or fund a share from the public budget. Each lever eases one pressure and creates another. A reform that moves contributions into funded accounts still has to pay rights built under the PAYG system.",
      items: [
        { number: "01", title: "More people in work", body: "Employment, less interrupted careers and migration widen the contribution base. The effect depends on how many people work, how much they earn and how long they stay in work." },
        { number: "02", title: "More value per hour", body: "The 2024 Ageing Report treats productivity growth as an assumption. In its weaker sensitivity, gross spending rises by about 0.6 GDP points relative to the baseline around 2060. Growth is an input, not a cheque." },
        { number: "03", title: "Different rules, visible costs", body: "Ages, rates, indexation, transfers and benefits change who pays, when and how much. The INPS Observatory on benefits and beneficiaries, referenced to 31 December 2024, records 31.9% of beneficiaries receiving two or more benefits and 1.6% of benefits worth at least EUR 5,000 gross per month. These are administrative categories, not proof of abuse." },
      ],
      note: "OECD Pensions Outlook 2022: moving contributions from PAYG to funded accounts leaves accrued PAYG rights to finance. During the transition, someone may pay twice through higher taxes, other spending cuts, more debt or lower benefits. These are accounting levers, not policy recommendations.",
    },
    closing: {
      title: "There is no end date.",
      accent: "There is a choice about who pays.",
      body: "The risk is not an explosion in one day. It is a promise that gets more expensive as contributors fall and beneficiaries rise. INPS's 2025 accounts record EUR 294.194 billion in contribution revenue, EUR 165.419 billion in state transfers and EUR 325.067 billion in INPS pension outlays. These are competence accounts with different perimeters, not the balance of the whole state and not proof that every pension is funded only by contributions.",
      sourcesIntro: "Observed figures come from INPS accounts and observatories. Projections come from the European Commission Ageing Report prepared with MEF and RGS and from Istat. Every projection depends on rules, births, migration, employment, productivity, inflation and longevity.",
      sourceList: "Primary sources and perimeters",
      sourceLinks: [
        { label: "European Commission, MEF and RGS, 2024 Ageing Report, Italy country fiche", year: "2024", url: "https://economy-finance.ec.europa.eu/document/download/82b762d7-21ce-4992-aa97-888fd2c66205_en?filename=2024-ageing-report-country-fiche-Italy.pdf" },
        { label: "Istat, Demographic indicators 2025, provisional births and fertility", year: "2026", url: "https://www.istat.it/en/press-release/demographic-indicators-year-2025/" },
        { label: "Istat, population and household projections, base 1/1/2024", year: "2025", url: "https://www.istat.it/en/press-release/population-and-household-projections-base-1-1-2024/" },
        { label: "INPS, General Accounts 2025", year: "2026", url: "https://www.inps.it/content/dam/inps-site/pdf/allegatinews/Relazione_rendiconto_generale_2025.pdf" },
        { label: "INPS, pensions and beneficiaries at 31 December 2024", year: "2025", url: "https://servizi2.inps.it/servizi/osservatoristatistici/api/getAllegato/?idAllegato=1007" },
        { label: "OECD, Pensions at a Glance 2025, Italy", year: "2025", url: "https://www.oecd.org/en/publications/pensions-at-a-glance-2025-country-notes_8a53ef12-en/italy_3dd0d4fa-en.html" },
        { label: "OECD, Pensions Outlook 2022, asset-backed reform transition costs", year: "2022", url: "https://www.oecd.org/en/publications/oecd-pensions-outlook-2022_20c7f443-en/full-report/component-4.html" },
      ],
      privacy: "No personal data is sent or stored. All four controls stay in the browser.",
    },
  },
} as const;

export const getStoryCopy = (language: Language) => STORY_COPY[language];
